excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kwanz.github.io
title: Z Kwan
tagline: tech notes and random thoughts
description: I tried to put some great song lyrics in the description, but I just couldn't remember the one that I used to have in mind
paginate: 5
