excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://kwanz.github.io
title: Z Kwan
tagline: tech notes and random thoughts
description: A letter once composed, seven years long and as tall as a tree
paginate: 5
